name: Deploy to AWS S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: NodeJS Setup
        uses: actions/setup-node@v1
        with: 
          node-version: 16.20.2
 
      - name: Dependency Installation
        run: npm install 

      - name: App Build
        run: npm run build

      - name: AWS Config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy
        run: aws s3 sync build s3://react-deployment-bucket-9925 --delete

